[package]
name = "rays"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
approx = "0.5.0"
env_logger = "0.9.0"
glam = "0.20.1"
image = "0.23.14"
log = "0.4.14"
rayon = "1.5.1"
